# Auth
@URL = http://localhost:3001
@TOKEN = null

###
# @name Register a new user
POST {{URL}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "name": "Admin",
  "email": "admin@example.com"
}

###
# @name Login user with username and password
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
# @name Returns user profile data
GET {{URL}}/auth/profile
Authorization: Bearer {{ TOKEN }}

###
# @name Try to enter protected route without token
GET {{URL}}/auth/profile
